const theme = {
  fonts: {
    body: 'Quicksand, sans-serif',
    heading: 'Della Respira, serif',
    fatserif: 'Suez One, serif',
    monospace: 'Roboto Slab, monospace',
    harmattan: 'Harmattan, sans-serif',
    sanserif: 'Montserrat, sans-serif',
    courgette: 'Courgette, serif',
    goudy: 'Sorts Mill Goudy, serif',
    book: 'Gentium Book Basic, serif',
    barlow: 'Barlow, sans-serif',
    inter: 'Inter, sans-serif'
  },
  fontSizes: {
      'microscopic': '1.1vmin',
      'miniscule': '1.25vmin',
      'teensy': '1.5vmin',
      'tiny': '1.75vmin',
      'small': '2vmin',
      'medium': '4vmin',
      'large': '6vmin',
      'huge': '8vmin',
      'colossal': '12vmin',
    },
  fontWeights: {
  body: 500,
  heading: 700,
  },
  colors: {
    black: '#000',
    white: '#fff',
    transparent: 'rgba(0, 0, 0, 0)',
    light: '#EEFAFF',
    dark: '#080B1A',
    Purple: '#5257F7',
    Purple2: '#5170f6',
    Teal1: '#03cea4',
    Teal2: '#22fccf',
    Teal3: 'rgb(6,75,72)',
    Orange1: '#F7986A',
    Orange2: '#F7562D',
    Marigold: '#F7D239',
    DarkPurple: '#191B4D',
    DarkPurple1: '#131438',
    Grey: '#3D4849',
    Pink: '#d2426d',
    Pink2: '#a1264b',
    Pink3: '#f43a8b'
  },
  space: [0, 4, 8, 16, 32, 48],
  breakpoints: ['40em', '64em', '80em'],
}

export default theme
